spring:
    application.name: student-register
    data:
      redis:
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}
        password: ${REDIS_PASSWORD:}

logging.pattern.console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"